-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.cell_analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_cell_id uuid NOT NULL,
  parent_cell_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  temperature double precision,
  ndvi double precision,
  heat_score double precision,
  ai_summary text,
  main_cause text,
  suggested_actions jsonb,
  confidence double precision DEFAULT 0.0,
  image_url text,
  gemini_model text DEFAULT 'gemini-2.0-flash-exp'::text,
  created_at timestamp with time zone DEFAULT now(),
  mission_generated boolean DEFAULT false,
  user_id uuid,
  CONSTRAINT cell_analyses_pkey PRIMARY KEY (id),
  CONSTRAINT cell_analyses_child_cell_id_fkey FOREIGN KEY (child_cell_id) REFERENCES public.child_cells(id),
  CONSTRAINT cell_analyses_parent_cell_id_fkey FOREIGN KEY (parent_cell_id) REFERENCES public.parent_cells(id),
  CONSTRAINT cell_analyses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.child_cells (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_cell_id uuid NOT NULL,
  cell_id text NOT NULL,
  center_lat double precision NOT NULL,
  center_lon double precision NOT NULL,
  lat_min double precision NOT NULL,
  lat_max double precision NOT NULL,
  lon_min double precision NOT NULL,
  lon_max double precision NOT NULL,
  temperature double precision,
  ndvi double precision,
  heat_score double precision,
  cell_size_m double precision,
  pixel_count integer,
  is_hotspot boolean DEFAULT false,
  analyzed boolean DEFAULT false,
  ai_analysis_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT child_cells_pkey PRIMARY KEY (id),
  CONSTRAINT child_cells_parent_cell_id_fkey FOREIGN KEY (parent_cell_id) REFERENCES public.parent_cells(id)
);
CREATE TABLE public.discoveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  parent_cell_id uuid NOT NULL,
  location_name text NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  radius_m double precision NOT NULL,
  cell_size_m double precision NOT NULL,
  total_cells_viewed integer,
  hotspot_cells_found integer,
  avg_temperature double precision,
  avg_ndvi double precision,
  avg_heat_score double precision,
  image_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discoveries_pkey PRIMARY KEY (id),
  CONSTRAINT discoveries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT discoveries_parent_cell_id_fkey FOREIGN KEY (parent_cell_id) REFERENCES public.parent_cells(id)
);
CREATE TABLE public.missions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  parent_cell_id uuid,
  child_cell_id uuid,
  cell_analysis_id uuid,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  title text NOT NULL,
  description text,
  mission_type text,
  heat_risk_score double precision,
  required_actions jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'completed'::text, 'cancelled'::text])),
  points_earned integer DEFAULT 0,
  created_by_system boolean DEFAULT false,
  distance_to_user double precision,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  completed_by_user_id uuid,
  CONSTRAINT missions_pkey PRIMARY KEY (id),
  CONSTRAINT missions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT missions_parent_cell_id_fkey FOREIGN KEY (parent_cell_id) REFERENCES public.parent_cells(id),
  CONSTRAINT missions_child_cell_id_fkey FOREIGN KEY (child_cell_id) REFERENCES public.child_cells(id),
  CONSTRAINT missions_cell_analysis_id_fkey FOREIGN KEY (cell_analysis_id) REFERENCES public.cell_analyses(id),
  CONSTRAINT missions_completed_by_user_id_fkey FOREIGN KEY (completed_by_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.parent_cells (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cell_key text NOT NULL UNIQUE,
  center_lat double precision NOT NULL,
  center_lon double precision NOT NULL,
  bbox_min_lat double precision NOT NULL,
  bbox_min_lon double precision NOT NULL,
  bbox_max_lat double precision NOT NULL,
  bbox_max_lon double precision NOT NULL,
  child_cells_count integer DEFAULT 0,
  total_scans integer DEFAULT 0,
  last_scanned_at timestamp with time zone,
  landsat_scene_id text,
  sentinel_scene_id text,
  ndvi_source text,
  avg_temperature double precision,
  avg_ndvi double precision,
  avg_heat_score double precision,
  hotspot_percentage double precision,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT parent_cells_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username text UNIQUE,
  avatar_url text,
  points integer DEFAULT 0,
  level integer DEFAULT 1,
  missions_completed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  accuracy double precision,
  context text CHECK (context = ANY (ARRAY['exploring'::text, 'mission'::text, 'analyzing'::text])),
  mission_id uuid,
  parent_cell_id uuid,
  recorded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_locations_pkey PRIMARY KEY (id),
  CONSTRAINT user_locations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_locations_mission_id_fkey FOREIGN KEY (mission_id) REFERENCES public.missions(id),
  CONSTRAINT user_locations_parent_cell_id_fkey FOREIGN KEY (parent_cell_id) REFERENCES public.parent_cells(id)
);